pool_info:
  default_res: Chinilla reference pool
  name: The Reference Pool
  logo_url: https://www.chinilla.com/img/chinilla_logo.svg
  description: (example) The Reference Pool allows you to pool with low fees, paying out daily using Chinilla.
welcome_message: "Welcome to the reference pool!"
pool_fee: 0.01
block_claim_fee: 0
pool_url: http://10.0.0.45
min_difficulty: 10
default_difficulty: 10
default_target_address: hcx1f8nyqfuusq3m72v39t3eknmd6sgyw03hhmfduv9yzl8ntwc9ehzsxraqhg
pool_fee_address: hcx1rd4khgjh7wyd3d62gry5msmfwv0gnmd7jgm8tgakr0t8as2q6qpq5e2ux0
wallet_fingerprint: 3967641394
authentication_token_timeout: 5
wallet_id: 1
node_rpc_port: 43555
wallet_rpc_port: 43256
partial_time_limit: 25
partial_confirmation_delay: 300
scan_start_height: 1000
collect_pool_rewards_interval: 600
confirmation_security_threshold: 32
payment_interval: 600
max_additions_per_transaction: 400
number_of_partials_target: 300
time_target: 86400
relative_lock_height: 32
logging:
  log_path: /var/log/chinilla
  log_filename: pool-server.log
  log_level: INFO
  log_maxfilesrotation: 7
  log_stdout: false
server:
  server_host: 0.0.0.0
  server_port: 80
  server_use_ssl: false
  server_ssl_crt: config/ssl/domain/domain_srv.crt
  server_ssl_key: config/ssl/domain/domain_srv.key
